### ISSUE TITLE
Can't find and start app

### ISSUE THREAD

**Issue by nikolicpetar17** [AudioBand/AudioBand#105]
When I install app I can't find it anyware on pc, only audioband file is the dowloaded one

**Comment by svr333** [comment]
it is in the taskbar, you right click on the taskbar and go to toolbars
![image](https://user-images.githubusercontent.com/35664724/230656642-e1708fdc-2534-4bfe-9cff-c612bbb52bd4.png)

If you dont see this you need to follow the instructions on <https://audioband.github.io/AudioBand/audioband/Windows11.html> because you need to modify your taskbar on windows 11 first
