### ISSUE TITLE
INVALID_CLIENT: Invalid redirect URI

### ISSUE THREAD

**Issue by arcticzay** [AudioBand/AudioBand#110]
ive followed a [different issue](https://github.com/AudioBand/AudioBand/issues/8) where someone had fixed it by removing the 80 from the localhost url and it didnt work for me and now im utterly confused

**Comment by TechSupport26** [comment]
Can you please provide a little more detail.
- There is a log file in the %temp% folder that may provide some answers.
- Was Spotify working before?
- What version of AudioBand are you using?
Thanks.

**Comment by arcticzay** [comment]
the temp log file didnt help much and spotify was working before yes
im using the latest version of audioband provided by the release channel

**Comment by arcticzay** [comment]
Ill provide the log file and i have the spotify app aswell as my client secret and ID are correct
Im on windows 10 since windows 11 never worked on my PC
[AudioBand.log](https://github.com/AudioBand/AudioBand/files/11674337/AudioBand.log)

**Comment by TechSupport26** [comment]
Has a success screen popped up at all?
Can you try using Spotify on a browser. See if that changes anything.

Can you try using this localhosthttp://localhost/callback in the Spotify developer dashboard.
You can try restarting your computer. Or AudioBand by restarting Explorer if you would like.

**Comment by arcticzay** [comment]
no success at all ill try on a browser and i tried with that redirect url and got the same error
what port should i change audioband to if that makes a difference
no luck with browser spotify either. same with restarting audioband

**Comment by TechSupport26** [comment]
Perhaps try rotating the client secret.
![image](https://github.com/AudioBand/AudioBand/assets/65631811/65bfdfef-8f7a-436d-8968-95cfae4e77f7)

Otherwise you can try create a new app for AudioBand and use fresh Spotify Client Secret and ID


There is the possibility that it is a firewall issue in windows. I had to allow explorer through private networks although I would do that as a last resort, and if it does not work then change it back.
