### ISSUE TITLE
Progress bar doesnt change position in music

### ISSUE THREAD

**Issue by Tubz786** [AudioBand/AudioBand#128]
## Description
So I've been using audioband with Spotify which has a Spicetify modification. And everything works but when I move the progress bar, it goes back to its original position and doesn't change the position of the music. I saw a post before #47 about this and apparently, the bug was fixed/is being fixed. I may have a setting wrong or forgotten to do something but I'm not sure. 

## How To Reproduce
Open Spotify
Play something
Try to move the progress bar in taskbar
Doesn't stay or change music

## Version
- Edition	Windows 10 Pro
Version	22H2
Installed on	‎16/‎08/‎2023
OS build	19045.3930
Experience	Windows Feature Experience Pack 1000.19053.1000.0

 - AudioBand Version 1.2.3

**Comment by svr333** [comment]
In order to use this feature you need Spotify Premium (this limitation is from Spotify and we cannot do much about it)

**Comment by Tubz786** [comment]
I see, even with the use of Spicetify which gives me the features of premium it won't work. Thanks for the quick reply btw. Much appreciated.

**Comment by svr333** [comment]
Sadly enough even with Spicetify it doesn't work. Normally none of the features (skipping, pausing, previous etc) dont work without premium, but we found a way to work around a few of them

Though there is a semi workaround, because Spotify does implement the Windows protocol which means the Windows 10 audiosource also works with Spotify, and the seek does work but things like volume and hearts dont work, as well as updating the info about current song is slower and often lags, so it is a trade off you can make

hopefully some day we can get best of both worlds, but for now those are the 2 options

*Do note that for Windows 10 audiosource to work with Spotify, you need to have the media hardware keys option enabled in Spotify's settings*

**Comment by Tubz786** [comment]
Surprisingly, it doesn't lag and is faster than when the audio source is Spotify. And I never used the hearts and volume so doesn't affect me. The only part that's a bit annoying is that it shows the Spotify logo underneath the picture. Not anything bad but looks off and also when hovering over it. Is there a way to manually edit how it shows? Regardless, Thanks a lot though I appreciate it. And thanks for making Audioband, massively useful!

Have a good one mate!

**Comment by Tubz786** [comment]
I'd rather not distract myself from my studies and my due projects, but I will come back to this in the future if it's not fixed, it will prove to be a nice little project. Again I appreciate your help.
Take care!

**Comment by svr333** [comment]
Haha a wise man, I continued this project during my studies as a way of procrastinating them, was fun :)
Youre welcome and you take care too, good luck with your studies
