### ISSUE TITLE
Add border radius on the buttons

### ISSUE THREAD

**Issue by Pandede** [AudioBand/AudioBand#34]
Thanks for this powerful plugin for music lover. However, the following points about the UI should be enhanced:
1. Add the border radius on the buttons
2. Improve the settings layout, the font is too large
3. Create the stylish profile which matches the style of each music player. For example, render the green button text if the audio source "Spotify" is selected.

**Comment by svr333** [comment]
@Pandede suggestion 2 and 3 are very straight forward, but what exactly do you mean with adding the border radius?

**Comment by Pandede** [comment]
![image](https://user-images.githubusercontent.com/38829000/152630862-04d87370-2237-40a2-94c4-e28f8be552e4.png)
Thanks for your reply! `border-radius` is one of the attribute name in CSS language, which means the rounded corners of the button. The current shape of button is a solid rectangle, It'll be prettier if it was a rounded rectangle.

**Comment by svr333** [comment]
Ah all right, that shouldn't be hard to add, I'll try to include it in next release.
Regarding the time on your other two items, Im currently the only one developing so I have to prioritize certain features.

Improving the settings layout will be done ever so slightly next release, but Im planning a big revamp in #44.
You can track its state there (this will take a few months seeing as I have to learn quite a few concepts for this too, and designing also takes a while).

Regarding number 3, I like the idea of this feature and I will implement it so that you can choose to auto select a certain profile when you switch to a new audiosource.
For example, in the settings menu, in your case you'd choose:

When "Spotify Audiosource selected" switch to "Spotify Profile"

This is also a relatively small feature that I like quite a lot, Im pretty sure I can find the time to put it in the next release as well.

**Comment by Pandede** [comment]
As I'm unfamiliar to C#, maybe you can implement an example and I do it for the rest 🤣

**Comment by svr333** [comment]
I didn't mean you had to code anything, unless you want to (always really appreciated :) )
If you want to Im always willing to help you out a bit with the layout, might be easiest to hit me up on discord if you have that.

If you don't want to spend the time in Ill probably get the features in relatively soon, and for the settings, you can track #44 to see how that is going

**Comment by svr333** [comment]
CornerRadius (border-radius in css) has been implemented and will be in the next release
![image](https://user-images.githubusercontent.com/35664724/154814464-8a5d7152-bbe4-473d-9893-2cd25375726a.png)

**Comment by svr333** [comment]
Closing since:
1. is implemented
2. is somewhat improved and will be fully revamped in #44
3. Open in #59, automatic coloring is unlikely to be implemented, but with automatic profile switching you can make a profile for each audiosource
