### ISSUE TITLE
Open sound source by clicking on the taskbar

### ISSUE THREAD

**Issue by guspimentel** [AudioBand/AudioBand#51]
As a user, I want to be able to open the audio source app that is currently playing in order to change a song, for example.

Example: A song is playing through Spotify, I click on the taskbar box and then the Spotify app opens up

**Comment by svr333** [comment]
This can be done by double clicking on anything that isnt a button

**Comment by svr333** [comment]
Closing because already implemented, if you meant something else or would like to expand, feel free to reopen

**Comment by imaginarny** [comment]
This isn't working for me. Double click doesn't open Spotify unless its already in taskbar. So maximize works, not opening. When Spotify is running in system tray, it's not working. This might be different story with Spotify installed as Win32 exe and app from MS Store. The latter one here.

Can you specify @guspimentel your case and if it's still present for you?

**Comment by svr333** [comment]
Make sure you're on the latest version, and that you have the following setting enabled inside of the Custom Mouse Bindings
![image](https://user-images.githubusercontent.com/35664724/185920752-48211a4f-3c29-45c2-babe-748726faa6d5.png)

**Comment by imaginarny** [comment]
I'm on the latest version and binding settings are enabled. As I stated, double click works as maximize when Spotify is already in taskbar. But won't open when minimized in system tray. So binding shouldn't be an issue.

![image](https://user-images.githubusercontent.com/20380121/185933159-d1661479-0c08-469b-ab1a-357c65c1632f.png)
![image](https://user-images.githubusercontent.com/20380121/185933360-50f230da-e18d-47b7-a4fe-835a52729e17.png)

**Comment by imaginarny** [comment]
By checking the related code, I'm positive now that issue is specified to MS Store app version of Spotify and its executable path.

https://github.com/AudioBand/AudioBand/blob/44d5e7744d894c3ed37c5c826c1debe6cf613897/src/AudioBand/UI/Toolbar/MouseBindingsViewModel.cs#L306-L307

In MS app version Spotify.exe, which is not accessible/executable by users, is located in a similar path such as:
```
C:\Program Files\WindowsApps\SpotifyAB.SpotifyMusic_1.191.824.0_x86__zpdnekdrzrea0
```

Which is not suitable for the used method. Although, Spotify UWP app should be able to be opened by the protocol. I could try to take a look into it as fix should be easy, if you want. Would also open a new issue, now that it's clarified.

**Comment by svr333** [comment]
My bad, for some reason I thought you mentioned you didn't use the MS App.
But yes, Microsoft handles apps installed directly from the store quite weirdly and after looking into it for a bit, I gave up on it.

Feel free to open a new issue, would love for your addition to open it through Spotify's custom protocol.
