### ISSUE TITLE
Audioband with Spotify integration does not allow removing songs from liked

### ISSUE THREAD

**Issue by denwi** [AudioBand/AudioBand#94]
## Description
With Spotify integration, dislike button does nothing

## How To Reproduce
1. Listen to a song on Spotify
2. Like song or switch to song that was previously liked
3. Try to press like button again to dislike

## Version
 - Windows 10 version 19044 (21H2)
 - AudioBand Version 1.2.1

## Logs/Screenshots Attachment

At the bottom onf AudioBand.log, I can see:
`2022-11-21 09:26:47.6332 | WARN | AudioSource(Spotify) | Something went wrong with player command [AddLike].
2022-11-21 09:27:37.8035 | WARN | AudioSource(Spotify) | Something went wrong with player command [AddLike].
2022-11-21 09:28:34.5330 | ERROR | AudioSource(Spotify) | {
  "error": {
    "status": 503,
    "message": "Service unavailable"
  }
}
2022-11-21 09:28:51.7876 | WARN | AudioSource(Spotify) | Something went wrong with player command [AddLike].
2022-11-21 09:32:40.8055 | WARN | AudioSource(Spotify) | Something went wrong with player command [AddLike].`

Perhaps it is trying to continuously add likes, and maybe not sending dislike command?

**Comment by TechSupport26** [comment]
Looks like Spotify's service for unliking a song is not available as it is throwing a 503 error.

https://developer.spotify.com/documentation/web-api/
Service Unavailable - The server is currently unable to handle the request due to a temporary condition which will be alleviated after some delay. You can choose to resend the request again.

We may just have to wait for them to sort it out or there may be something we can do. I am not sure at the moment but I will look at is a little later.

**Comment by TechSupport26** [comment]
Just an update. At the moment you should be able to like and dislike again. It is logging a warning but I think that might not be correct.
